### ISSUE TITLE
tank-to-wheel E consumption ICEV-p's

### ISSUE THREAD

**Issue by floriandierickx** [romainsacchi/carculator#19]
Hey,

I'm (starting to) exploring your rrreally cool LCA-modelling project (congratulations and thank you for developing this, this is what everybody needs!). 

I don't know if this is the right place to ask these types of questions (I also tried on [Twitter](https://twitter.com/FlorianDRX/status/1400919817834614784?s=20), but I have the impression that that medium is not the most frequently visited ;)), but:

On page 21 of your [preprint](https://www.psi.ch/en/media/57994/download), you mention that the tank-to-wheel E consumption of petrol fuelled ICEVs might decrease with 48 % by 2050 (180 gCO2/km -> 91 gCO2/km) due to decrease in curb mass (-8.5 %) and increase in powertrain and engine efficiency (+50%). I'm not sufficiently qualified in ICE combustion engine technology, but I was wondering on which paper/database/forecast this projection is based on (especially the powertrain/engine efficiency evolution) ? Intuitively, I would expect a rather constant engine efficiency, considering decades of ICE development. Or am I too naive and are carmakers only now starting to consider the fuel efficiency of their cars? :p

If you have time, I would be happy to get to know a bit more about this assumption, as I am intrigued by the forecast (at least for some countries) that in the long term ICEVs emission intensity might converge with those from BEV (as indicated in Figure 9 on p. 22 of the preprint):

<img width="614" alt="Screenshot 2021-06-04 at 23 10 23" src="https://user-images.githubusercontent.com/12695083/120862933-4ab4a700-c579-11eb-9eb3-20aca58dc674.png">

**Comment by romainsacchi** [comment]
Hi @floriandierickx ,

thanks for your interest. Well, maybe I should start saying that this pre-print is getting old. Unfortunately, the journal we submitted it to is veeeeerrrry slow. In the meanwhile, we brought several improvements to the model.

In any case, we still do consider an increase in the ICEVs engine efficiency, but not by 50%, but rather around 35%.

A typical mid-size petrol car would go from a tank-to-wheel efficiency of 22-23% in 2020 to about 30% by 2050.

It is not really because we think combustion engines will get better, but rather because there is a progressive hybridization of the powertrain: the combustion engine being increasingly assisted by a small electric motor allows to reduce the size of the engine. By reducing the size of the engine and its power, we increase the share of the driving time operated at a higher load point, where such engines are most effective, thereby increasing its efficiency. We think it is the only way ICEV could still exist in the future, if they ever will be.

By default, I think ICEVs reach a hybridization level of 15% by 2050 (15% of the power is provided by an auxiliary electric motor). This being said, one can completely deactivate this assumption in the online tool or the python library.

**Comment by floriandierickx** [comment]
Thank you for the clear explanation, it helped me better understand the hybridisation principle as described in the documentation ([hypothesis](https://hyp.is/O6M3VsiNEeuOOceCEEfmDg/carculator.readthedocs.io/en/latest/modeling.html)) and how to disable it ([hypothesis](https://github.com/romainsacchi/carculator/issues/modeling)).
