### ISSUE TITLE
quick results for Belgium seem way off for EVs

### ISSUE THREAD

**Issue by dominiquedemunck** [romainsacchi/carculator#21]
Hello

Impressive tool which can really be helpful!
I didn't do a dive in the data or code, but the quick results for Belgium (new cars), give only a 20% advantages for EVs compared to Diesel:
https://carculator.psi.ch/display_quick_results/BE

![image](https://user-images.githubusercontent.com/14312314/120979203-a481c080-c775-11eb-86c3-d4de27fc21a4.png)

This would contradict other recent estimates like:
https://www.transportenvironment.org/what-we-do/electric-cars/how-clean-are-electric-cars
![image](https://user-images.githubusercontent.com/14312314/120979545-00e4e000-c776-11eb-95b7-9ccf91195ace.png)

or:
https://www.carbonbrief.org/factcheck-how-electric-vehicles-help-to-tackle-climate-change 

and also this tool:

https://climobil.connecting-project.lu/
![image](https://user-images.githubusercontent.com/14312314/120979992-6c2eb200-c776-11eb-9bf6-b4bbe78acfa7.png)

**Comment by floriandierickx** [comment]
Hey, I allow myself to jump into this conversation/question (in complement to our exchange on [Twitterrr](https://twitter.com/FlorianDRX/status/1401828849822928900?s=20), including with @thomasgibon).

Excuses for the rather 'lazy' reflection (I did not delve into all the 'nitty-gritty' details of either carculator or climobil, apart from a quick scan for methodology, energy system trajectory data), but: could it be that the two approaches can be broadly distinguished by:

- Carculator: input-output/LCA matrix using Ecoinvent/... (resulting reflection: to which extent is Ecoinvent up to date?). Did you also include other databases (ex. sectoral exchanges represented in IO databases, ...) ?
- [Climobil](https://climobil.connecting-project.lu/?batteryLifetime=240000&batteryCapacity=30&greenhouseGas=65&electricCarRange=250&carbonElectricityMix=300&greenhouseBattery=30&greenhouseWTT=25&greenhouseTTW=150&batteryPenalty=0.9&annualMileage=20000&ICECurb=1551&ECurb=1977&NEDCpenalty=0.39&decarbonization=0): compiling recent existing LCA studies, tailored to a specific context/supply chain

**Comment by thomasgibon** [comment]
Hi all! Thanks for the interest.

1. First off, climobil is clearly _much_ simpler than carculator. Our website lets you manipulate various parameters that are then multiplied with fixed (e.g. in the case of emissions embodied in manufacturing) or variable emission factors. What you get is the result of a linear combination. What you get in carculator can be literally based on a full-scale LCA if you so choose.
2. Carculator models vehicle archetypes (I think? i.e. small, mid-size, SUV...) whereas Climobil lets you choose weight/emissions or specific model, did you make sure to choose equivalent cars before comparing?
3. Real-world emissions are estimated in climobil (we simply estimate that emissions are ~39% higher than NEDC-declared, following an ICCT publication), but they are actually calculated in carculator (again, @romainsacchi will probably clarify) - I am assuming this entails a potentially big difference for the emissions of the ICE.
4. We do not credit GHG emissions at any step (neither for using recycled material at production, or for providing recyclable material at the end-of-life treatment stage), this might play a role too...

There are probably other reasons, but that's already what I can think of from the top of my head.

**Comment by floriandierickx** [comment]
Hey @thomasgibon, thank you for these insights. I hope to find time to dive deeper in the models and start with, for example, comparing a similar case study and get back to this list to better understand the scope and modelling frameworks.

**Comment by romainsacchi** [comment]
@thomasgibon @floriandierickx @dominiquedemunck Also, there's maybe the fact that for Belgium during that period, the model considered 7% bioethanol and 5% ioiodiesel in the blend (reducing direct GHG emission by that much) -- I got these blends from the IEA's World Extended Energy balance.

**Comment by floriandierickx** [comment]
Hey @romainsacchi, thanks a lot for your answers (althought it was not my question, I think I can say that for all present here :) ). 

I went briefly through the EU Reference Scenario 2016, and I have been looking into comparing it with other projections specifically for Belgium (although the network is interconnected and influenced by electricity exchange, another question to tackle..). I don't have a tangible result yet, but broadly speaking, I think it is a good representation of reality and future prospect (gas is currently projected to increase in the coming years because of a planned phase-out of nuclear). I will try to get other numbers to compare with (from other scenario's such as Belgium 2050: [abstract](https://klimaat.be/doc/climate-neutral-belgium-by-2050-summary.pdf) online, more details upcoming), the grid manager (Elia), etc..) and experiment with how it influences the results. Also the shares of bioenergy are indeed a really important aspect, but I'm - for now - technically not sufficiently knowledgeable on that matter.

Interesting to learn about the details on the Ecoinvent update as well. I know that Ecoinvent is an authority in LCA databases, but it's only a pity that it's not open (although I might be mistaken here, as I did see an open version that enables consultation of individual processes online on the ecoinvent-website, which might be used to go through the assumptions of carculator?). I did experiment with it in the past, but curious to dive deeper... :))

> Last but not least, we will soon update the model as we have received new calibration data from the European Commission's CO2 test database for 2019 vehicles, but this will mostly make ICEVs a bit more efficient (so this will decrease further the difference) than before (diesel and gasoline ICEVs are now close to 130g CO27km of direct emissions) ...

Linked with point 3 from @thomasgibon: related to the the ICCT 39 % estimated higher real-world emissions compared to the new WLTP cycle: an 'LCA Q&A'  from [Transport & Environment (2020)](https://www.transportenvironment.org/sites/te/files/downloads/FAQ%20T%26E%27s%20EV%20LCA%20tool_1.pdf.) [1] explains that they used a real-world emissions from the ​[spritmonitor.de](spritmonitor.de)​ database, in order to model the 10 most common car models on the market per category. I don't know the database, but it might not be capturing all the car types of the market (and therefore hard to use from a legislative point of view with decreasing-but-not-entirely-zero-emission norms, or for a really detailed LCA for each and every car on the market), but it might be interesting to compare with at some point ?

[1] T&E. “Frequently Asked Questions on T&E’s EV LCA Tool,” April 2020. https://www.transportenvironment.org/sites/te/files/downloads/FAQ%20T%26E%27s%20EV%20LCA%20tool_1.pdf, page 1:
> Regulatory lab test protocols (WLTP or NEDC) are not used here because they seriously underestimate real-world fuel consumption and therefore CO2 emissions (real-world test results diverge from lab tests by 39%, according to ​the ICCT​).
For diesel and petrol cars, we used the average real-world consumption (CO2 emissions) of the 2018 top 10 most-sold vehicles for each category.
Fuel and energy consumption is based on real-world consumption declared values from millions of drivers, taken from the ​spritmonitor.de​ database.

**Comment by romainsacchi** [comment]
Hi @floriandierickx,

to be precise, we use the EU's database to calibrate the vehicles' weight and we fine tune the different drivetrain compoentns' efficiencies until we match their fuel consumption values (which they get based on the NEDC driving cycle). So we do not use their FC values as they are, but instead there's a "calibrated" energy model which calculates the FC based on the weight, road gradient, engine, gearbox and axles efficiencies, rolling resistance, etc.

We thought about the spritmonitor data, but unlike the ICCT report, we found that the results look a bit biased. When one looks at gasoline or diesel cars present there, 60% are hybrid vehicles. Once you get rid of those, their FC is suspiciously low. We thought that maybe users that register their fuel consumption are somewhat incentivized to drive more economically. So, we decided in the end not to use it. I guess if spritmonitor grants you the access officially, they get you "cleaner" data, I don't know. I do have all the scrapped data though, if you are interested. Also, spritmonitor only have a few thousands of vehicles, which is insignificant compared to the 290+ million cars in Europe.

**Comment by romainsacchi** [comment]
Here is the sort of calibration we do for the vehicle mass per size class. There's about 15 million points per year, which we reduce down to average by car model.
![image](https://user-images.githubusercontent.com/22473067/121195463-e98a1d80-c86f-11eb-9bb9-161679fc8505.png)

And then we fine-tune efficiencies to match approximately their FC values using the NEDC driving cycle (red dots), and we show the WLTC-based values as well (orange dots).


![image](https://user-images.githubusercontent.com/22473067/121195822-3968e480-c870-11eb-8e25-6b50fa440f74.png)

**Comment by floriandierickx** [comment]
😮 So I understand you model your own emission/driving tests to the different driving test (NECP/WLTP) values ? That's really impressive.. This with the purpose of being able to modify different aspects/parameters of a 'generic' car in all detail, in order to derive the influence of each parameter on the impact indicators? (or maybe in case somebody wants to do an electric retrofit of his/her existing car and wants to lower the impact - I would then go for [a velomobile](https://www.lowtechmagazine.com/2012/10/electric-velomobiles.html), but still :p ). I have yet to look into the details of the calculations and documentation (I hope to find time for that..), thank you for the 'quick summary' and insights here.

I did find the explanation on the hybridisation ([hypothesis](https://hyp.is/O6M3VsiNEeuOOceCEEfmDg/carculator.readthedocs.io/en/latest/modeling.html)) and how to disable it ([hypothesis](modeling)) also in the documentation now.

Also thanks a lot for your insights in the spritmonitor database. For hybrid vehicles a big difference might not come as a surprise, so I'll 'touch with care' conclusions for ICEVs (including resulting reports) ... :)

**Comment by romainsacchi** [comment]
Hi @floriandierickx ,

indeed, the car model combined with the energy consumption model allows to completely parametrize the vehicle (no of passengers, engine efficiency, battery mass, frontal area) and its use phase (road gradient, speed profile, etc.). In the examples notebook, we show how to do a sensitivity analysis, where we change each input parameter individually by +10% and look at the effect on the GWP score. Here for example with a mid-size BEV: 
![image](https://user-images.githubusercontent.com/22473067/121342501-f8c9a380-c921-11eb-821e-5267ecbfc2b4.png)

**Comment by floriandierickx** [comment]
Cool! That's really insightful.. ! This would allow also to do a kind of 'best available/projected technology-impact analysis for each of the variables? This looks also really interesting to link to normative (EU 'average' emission norm regulation) and/or fiscal policy. It could also be argued that these variables are captured/embedded in these regulations, but for some it might be interesting to look a bit more in detail..

**Comment by dominiquedemunck** [comment]
@romainsacchi 

This might be helpful to make the tool more acurate:

1) The EU 2016 Reference publication is way too outdated because of huge market (price of offshore wind, solar) and policy evolutions (EU Green Deal, US aiming at 0 carbon electr in 2035, ... ).

This publication offers a recent and very detailed estimate of  CO2 intensities in Europe, with database available free for download (see download link at end of paper):
https://www.mdpi.com/1996-1073/14/8/2165

As referenced here https://twitter.com/SamHamels/status/1407243178294534147

Example data:

![image](https://user-images.githubusercontent.com/14312314/122903062-55c84f00-d34f-11eb-9744-54377b1246ff.png)

Note about why it's good to use average CO2 intensity (instead of marginal) you will find argumentation here https://twitter.com/AukeHoekstra/status/1407081827555233799

2) Since the weight of the mileage is in the first years of the car use, I would not use a fixed annual mileage, A better estimate is to use the official Dutch km values per year, which are a good EU proxy since the Netherlands have an average age fleet park. 

On average, Dutch cars do about 50% of the km's when they are younger then 8 years. 
You get 97% of km's driven by cars younger then 21 years. See datasheet referenced here (second tab) 
https://twitter.com/DominiqueDeMunc/status/1390035588850532364

Or summary:
<html>
<body>
<google-sheets-html-origin>

Cumulative part of kms | Total
-- | --
4.39% | 0 jaar
12.35% | 1 jaar
19.64% | 2 jaar
26.02% | 3 jaar
33.58% | 4 jaar
39.13% | 5 jaar
44.56% | 6 jaar
50.69% | 7 jaar
57.12% | 8 jaar
62.32% | 9 jaar
66.33% | 10 jaar
70.70% | 11 jaar
74.85% | 12 jaar
79.02% | 13 jaar
82.65% | 14 jaar
86.04% | 15 jaar
89.05% | 16 jaar
91.70% | 17 jaar
93.86% | 18 jaar
95.77% | 19 jaar
97.20% | 20 jaar


</body>
</html>

**Comment by romainsacchi** [comment]
Hi @dominiquedemunck ,

great find! I looked into the data and could not find the technology mix per country-year. I contacted the author to see if he'd be kind to share that with us - as we cannot directly use CO2 intensity factors. Update: by the time I'm writing this, the author replied with the electricity mixes (which are actually available [here](https://2020.entsos-tyndp-scenarios.eu/)). So, I'll open an issue about integrating this.

About marginal electricity mix: it seems to me that this person is missing the point, or that he maybe lacks a system perspective. Using the marginal mix is not about finding out which electricity providers will actually charge the battery of an EV at this time of the day in this region, or whatever. In LCA, or rather consequential LCA, it is about finding out which technology will react (by reacting, we mean investing in additional production capacity in additional to the regular rate of capital renewal) as a result of increasing the demand for electricity. We are not interested in knowing the origin of the electricity that enters the battery, but rather at the system changes that result from charging the battery. As long as the forecast for the electricity system properly account for the expect increase in electricity demand from heat pumps, BEVs, etc., I personally find it completely fine. If in a given country or network of interconnected grids, the RES are supposed to grow to face an increase in demand or a phasing out of old technologies, using a marginal mix made of these RES seems fine to me. They will expand because of the battery charging. In that regard, global energy systems can be very helpful to LCA of electric mobility.

About the annual mileage vs. age of the vehicle: that's interesting and I previously found data like this (COPERT and HBEFA). But I was never quite sure of the implementation: I guess we would still need to know the expected lifetime of the vehicle in km but also in years, and integrate that over some distribution to get the annual mileage per year of age. Also, the distribution you show is a fleet average: it won't fit cars with a life expectancy of 10 or 15 years, for example. I guess only a fraction of the fleet makes it to 20 years. Ideally, we would need a simple, yet representative, distribution of the km over the years that would adapt to the life expectancy indicated (in years). I'll open an issue about this task too! If you have a precise idea about this, please let me know.

Thanks for your inputs.

**Comment by dominiquedemunck** [comment]
I don't think the kind of very detailed vehicle km data your are looking for is readily available.

In this doc you will find attempts for estimates about EU vehicle lifetime and miles driven:
https://www.avere.org/wp-content/uploads/2020/09/englisch_Studie-EAuto-versus-Verbrenner_CO2.pdf 

The Dutch data remain my favorite, as this national fleet average, is quite representative for the average EU car.
If you use the Diesel data only, I think you get a good profile for high mileage drivers.

I noticed that google translate worked OK with the Dutch data:

https://translate.google.com/translate?hl=en&sl=auto&tl=en&u=https%3A%2F%2Fopendata.cbs.nl%2F%23%2FCBS%2Fnl%2Fdataset%2F83702NED%2Ftable%3Fts%3D1516822135004

Also note: cars are exported also a lot, especially the older ones out of the EU.
Even in Poland AVERAGE car age is 14 years!

https://www.acea.auto/figure/average-age-of-eu-vehicle-fleet-by-country/

**Comment by romainsacchi** [comment]
Hi @dominiquedemunck ,

regarding the electricity mix projected for Belgium, I just looked at the data from https://doi.org/10.3390/en14082165.
I normalized the generated volumes and graphed it using the baseline scenario called "National trends" (not enough to reach the Paris Agreement, but quite ambitious nevertheless). Here are the results for Belgium (% gross production mix, excluding trade): 
![image](https://user-images.githubusercontent.com/22473067/122948585-4e1e9f80-d37b-11eb-9c50-fd5af2eeeb3d.png)

So it does change quite a bit: here the disappearance of nuclear is not compensated by gas (as in the EU 2016 Reference Scenario) but by solar + wind (>70% of the gross production, and this is not even the ambitious scenario!). This seems huge. What does @floriandierickx think about this?

If these projections turn out to be good enough, we will use them.

**Comment by romainsacchi** [comment]
Hi @dominiquedemunck,

I updated the electricity mixes for European countries (incl. Belgium) based on ENTSO-E TYNPD report projections (https://2020.entsos-tyndp-scenarios.eu/), following the "National Trends" scenario (sort of baseline).
The km-weighted mix for BE (from 2020 to 2037) is now made of 55% renewable.

We now have a 35-40% GHG emissions improvement over a comparable gasoline car (https://carculator.psi.ch/display_quick_results/BE).

![image](https://user-images.githubusercontent.com/22473067/128676756-fff66fa7-296c-4d3e-b9ba-2e398253e690.png)

But this is admittedly still quite different from this T&E graph: 
![image](https://user-images.githubusercontent.com/22473067/128676870-425319e5-c798-455a-87a1-b23da75de664.png)

Hence, to be investigated further.
