### ISSUE TITLE
Can't reproduce documentation example for mass pie chart

### ISSUE THREAD

**Issue by cmutel** [romainsacchi/carculator#25]
following https://carculator.readthedocs.io/en/latest/validity.html#car-and-components-masses

With a new environment, installing from pip on Nov. 5, I get:

<img width="907" alt="Screenshot 2021-11-05 at 10 49 18" src="https://user-images.githubusercontent.com/645217/140491786-f944a695-d14d-44e0-9d7c-262d4c04bbc0.png">

Maybe the parameter names changed?

**Comment by romainsacchi** [comment]
It's because I omitted the method call `.set_all()` in the script to produce that pie chart (without that, it's an empty car).
Calling `.set_all()` before plotting, I can reproduce the chart:

![image](https://user-images.githubusercontent.com/22473067/142429531-9155a0a1-07fa-419b-ae61-0b1bfb7b3ed2.png)


I will correct the script in the documentation whenever I find some time. Thanks.
