### ISSUE TITLE
Importing carculator database to Activity Browser

### ISSUE THREAD

**Issue by djuch** [romainsacchi/carculator#27]
Hi there,

Currently, I am trying to import a Carculator excel file into Activity Browser (which runs on Brightway 2). However, when I try to import the excel file as a database, the whole AB environment shuts down. It might be that it's due to missing biosphere flows? @marc-vdm mentioned I could perhaps post the issue here. The reason I am trying to import the file is to get a relevant database to perform an LCA on EV technologies, as evoinvent does not include all EV related data.

What I did: 
- I picked the advanced configurator on the Carculator website.
- I made two comparisons between electric and petrol vehicle for a 2022 and 2030 scenario.
- I calculated the results and exported the inventory database to an excel file (and did not modify the file).
- Then, I tried importing the file to the AB environment, however, then it shuts down and does not import the excel file.

A link to the excel file that I am trying to import to AB: 
[carculator_inventory_2022-04-13_for_ei_3.8_brightway2.xlsx](https://github.com/romainsacchi/carculator/files/8486827/carculator_inventory_2022-04-13_for_ei_3.8_brightway2.xlsx)

Do you know what I can do to fix this?

Thanks in advance!

**Comment by romainsacchi** [comment]
Hi @djuch ,
sorry for the late answer. Yes, Activity Browser in my experience, is not very good at importing stuff.
I suggest to do it directly in Python, like so (also illustrated in the carculator [examples notebook](https://github.com/romainsacchi/carculator/blob/master/examples/Examples.ipynb)):

````

import brightway2 as bw
import bw2io
bw.projects.set_current("your_bw_project")

fp = r"/Users/romain/Downloads/carculator_inventory_2022-04-13_for_ei_3.8_brightway2.xlsx"
i = bw2io.ExcelImporter(fp)
i.apply_strategies()

i.match_database(fields=('name', 'unit', 'categories', 'location'))
i.match_database('ecoinvent 3.8 cutoff', fields=('name', 'unit', 'location', 'reference product'))
i.match_database("biosphere3", fields=('name', 'unit', 'categories'))
i.statistics()

```

There, you will see that you still have some unmatched biosphere flows: those flows are not natively in the `biosphere3` database (noise flows, mostly). If you want them, you can incorporate them either by creating an additional biosphere database that you then link to like the above procedure (doing first ``i.create_new_biosphere(name="additional biosphere")``), or by integrating them into your `biosphere3` database, doing ``i.add_unlinked_flows_to_biosphere_database()`` (preferred option I'd say).
Otherwise, if you do not need them, you can drop them:

```
i.drop_unlinked(i_am_reckless=True)
i.statistics()

241 datasets
2559 exchanges
0 unlinked exchanges
```

and then write the  database:
```
i.write_database()

Writing activities to SQLite3 database:
0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:00:00
Title: Writing activities to SQLite3 database:
  Started: 04/23/2022 11:12:37
  Finished: 04/23/2022 11:12:38
  Total time elapsed: 00:00:00
  CPU %: 52.50
  Memory %: 3.88
Created database: carculator export
```

and there, you'll be able to do our LCAs :-)

<img width="923" alt="Screenshot 2022-04-23 at 11 19 51" src="https://user-images.githubusercontent.com/22473067/164888507-8ea86937-4950-4bb6-acab-471919c3be7f.png">

**Comment by marc-vdm** [comment]
Thanks for pointing this out, I've made it an issue on AB.
